### ISSUE TITLE
后面有涉及磁盘存储吗

### ISSUE THREAD

**Issue by IAliceBobI** [nkbai/learnrustbynats#2]
后面有涉及磁盘存储吗

**Comment by nkbai** [comment]
为什么会有存储的，就是一个消息发送，
后面我做了优化，但是没有讲

**Comment by Zhanghailin1995** [comment]
> 为什么会有存储的，就是一个消息发送，
> 后面我做了优化，但是没有讲

能否把优化部分也讲一讲呢，在b站看到您的视频，觉得讲的很好，或者在您的博客里面写一下优化的要点。

**Comment by nkbai** [comment]
优化的部分代码里有，只是没讲而已
